=== HuangRogerInfo/XML1/projet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="ligne">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="gares" maxOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="gare" maxOccurs="unbounded">
                  <xs:complexType mixed="true">
                     <xs:attribute name="id" type="xs:ID" use="required"/>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        
          <xs:element name="variantes" maxOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="variante" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:attribute name="id" type="xs:ID" use="required"/>
                    <xs:attribute name="gares" type="xs:IDREFS" use="required"/>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        
          <xs:element name="trains" maxOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="train" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="trajets" maxOccurs="1">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="trajet" maxOccurs="unbounded">
                              <xs:complexType>
                              <xs:sequence>
                                <xs:element name="depart">
                                <xs:complexType>
                                  <xs:attribute name="gare" type="IDREF"/>
                                </xs:complexType>
                                </xs:element>
                                <xs:element name="terminus">
                                  <xs:complexType>
                                    <xs:attribute name="gare" type="IDREF"/>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="horaires" maxOccurs="1">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="horaire" maxOccurs="unbounded">
                                        <xs:complexType mixed="true">
                                          <xs:attribute name="gare" type="xs:IDREF" use="required"/>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                </xs:sequence>
                                <xs:attribute name="var" type="xs:IDREF" use="required"/>
                              </xs:complexType>
                            </xs:element>  
                          </xs:sequence>
                          <xs:attribute name="jours" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="LUNDI"/>
                                    <xs:enumeration value="MARDI"/>
                                    <xs:enumeration value="MERCREDI"/>
                                    <xs:enumeration value="JEUDI"/>
                                    <xs:enumeration value="VENDREDI"/>
                                    <xs:enumeration value="SAMEDI"/>
                                    <xs:enumeration value="DIMANCHE"/>
                                  </xs:restriction>
                            </xs:simpleType>
                          </xs:attribute>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                    <xs:attribute name="code" type="xs:ID" use="required"/>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
  
        </xs:sequence>
        <xs:attribute name="nom" type="xs:ID"/>
        <xs:attribute name="entreprise" type="xs:string" fixed="SNCF"/>
      </xs:complexType>
    </xs:element>
</xs:schema>

=== HuangRogerInfo/XML1/projet.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xslt.xml" type="application/xml"?>
<ligne nom="H" entreprise="SNCF" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projet.xsd">
  <gares>
    <gare id="g1">gare 1</gare>
    <gare id="g2">gare 2</gare>
    <gare id="g3">gare 3</gare>
    <gare id="g4">gare 4</gare>
  </gares>
  <variantes>
    <variante id="var1" gares="g1 g2 g3"/>
    <variante id="var2" gares="g1 g4 g3"/>
  </variantes>
  <trains>
    <train code="ELSA">
      <trajets jours="Lundi Mercredi">
        <trajet var="var1">
          <depart gare="g1"/>
          <terminus gare ="g3"/>
          <horaires>
            <horaire gare="g1">18:30</horaire>
            <horaire gare="g2">19:45</horaire>
            <horaire gare="g3">20:45</horaire>
          </horaires>
        </trajet>
        <trajet var="var1">
          <depart gare="g3"/>
          <terminus gare ="g1"/> 
          <horaires>
            <horaire gare="g3">20:50</horaire>
            <horaire gare="g2">19:45</horaire>
            <horaire gare="g1">23:00</horaire>
          </horaires>
        </trajet>
      </trajets>
    </train>
    
    <train code="ERIC">
      <trajets jours="Lundi Mercredi">
        <trajet var="var1">
          <depart gare="g1"/>
          <terminus gare ="g3"/>
          <horaires>
            <horaire gare="g1">20:30</horaire>
          </horaires>
        </trajet>
        <trajet var="var1">
          <depart gare="g3"/>
          <terminus gare ="g1"/> 
          <horaires>
            <horaire gare="g2">22:00</horaire>
          </horaires>
        </trajet>
      </trajets>
    </train>
  </trains>
</ligne>
